#!/usr/bin/env python3
from pathlib import Path
from json import load

if __name__ == "__main__":
    path_var = Path("/var/lib/n4d/variables/INTERNAL_INTERFACE")
    if path_var.exists():
        with path_var.open('r',encoding='utf-8') as fd:
            variable = load(fd)
            try:
                result = variable['INTERNAL_INTERFACE']['value'].encode('UTF-8')
                if result isinstance str:
                    print(result)
                elif result isinstance list:
                    print(" ".join(result))
                else:
                    print("")
            except:
                print("")
    else:
        print("")
